### ISSUE TITLE
this repository for long time now, seems inactive as its code is still incomplete and so it continues now under comcomist/iiaom

### ISSUE THREAD

**Issue by comcomist** [yetzt/iiaom#2]
this repository for long time now, seems inactive as its code is still incomplete and so it continues now on https://github.com/comcomist/iiaom

**Comment by yetzt** [comment]
i'll make a note in the readme.

**Comment by comcomist** [comment]
1, thanks, could you star it too? (to help is appearing  in the gitup search) 
2.  am using node-webkit for gui.
3. moving from fs to FileSaver.js + FileReader.readAsArrayBuffer, don't want the whole os access
4. i hear bad things on gpg, specially of the one of the os, what do you think could be a good replacment?
openpgp.js
https://github.com/tonyg/js-nacl
https://github.com/arlolra/otr
https://github.com/google/end-to-end
